SAF/src/Entity/StudyGroup.php
<?php

namespace App\Entity;

use App\Repository\StudyGroupRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=StudyGroupRepository::class)
 */
class StudyGroup
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $group_name;

    /**
     * @ORM\Column(type="string")
     */
    private $group_leader;

    /**
     * @ORM\Column(type="string")
     */
    private $subject;

    /**
     * @ORM\Column(type="datetime")
     */
    private $datetime_of_study_group;

    /**
     * @ORM\ManyToMany(targetEntity="Student", mappedBy="study_groups")
     */
    private $enrolled_students;

    public function __construct()
    {
        $this->enrolled_students = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getGroupname(){
        return $this->group_name;
    }

    public function setGroupname($group_name){
        $this->group_name = $group_name;
    }

    public function getGroupleader(){
        return $this->group_leader;
    }

    public function setGroupleader($group_leader){
        $this->group_leader = $group_leader;
    }

    public function getSubject(){
        return $this->subject;
    }

    public function setSubject($subject){
        $this->subject = $subject;
    }

    public function getDatetimeofStudyGroup(){
        return $this->datetime_of_study_group;
    }

    public function setDatetimeofStudyGroup($datetime_of_study_group){
        $this->datetime_of_study_group = $datetime_of_study_group;
    }

    public function getEnrolledStudents(){
        return $this->enrolled_students;
    }

    public function setEnrolledStudents(Student $enrolled_student){
        $this->enrolled_students[] = $enrolled_student;
    }
}

SAF/templates/views/edit_sgroup.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Study Group{% endblock %}

{% block body %}

            <div>s

        {{ form_start(form) }}

                {% for SGroup in form.study_groups %}

                        <div style="display: inline-block; width: 350px">
                            <div style="margin-bottom: 10px">
                                {{ form_row(SGroup.group_name) }}
                            </div>
                            <div style="margin-bottom: 10px">
                                {{ form_row(SGroup.group_leader) }}
                            </div>
                            <div style="margin-bottom: 10px">
                                {{ form_row(SGroup.subject) }}
                            </div>
                            <div style="margin-bottom: 100px">
                                {{ form_label(SGroup.datetime_of_study_group) }}
                                {{ form_widget(SGroup.datetime_of_study_group) }}
                                <div style="color: #ff0000">{{ form_errors(SGroup.datetime_of_study_group) }}</div>
                            </div>
                        </div>

                {% endfor %}


        {{ form_end(form) }}

    <a class="sgroups_back" href="{{ path('study_groups') }}"><button type="submit" style="background-color: #e97d43; border-radius: 5px ;border: 0; width: 80px; height: 25px; color: #ffffff; margin-top: 10px">Back</button></a>
    </div>

{% endblock %}

SAF/templates/views/edit_student.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Student{% endblock %}

{% block body %}

    {% for message in app.flashes('error') %}
        <div class="flash">
            <p>{{ message }}</p>
        </div>
    {% endfor %}

    <div>
        {{ form_start(form) }}

        {% for Student in form.enrolled_students %}

            <div style="display: inline-block; width: 450px">
                <div style="margin-bottom: 10px">
                    {{ form_row(Student.name) }}
                </div>
                <div style="margin-bottom: 10px">
                    {{ form_row(Student.sex) }}
                </div>
                <div style="margin-bottom: 10px">
                    {{ form_row(Student.email_address) }}
                </div>
                <div style="margin-bottom: 10px">
                    {{ form_row(Student.place_of_birth) }}
                </div>
                <div style="margin-bottom: 10px">
                    {{ form_label(Student.date_of_birth) }}
                    {{ form_widget(Student.date_of_birth) }}
                    <div style="color: #ff0000">{{ form_errors(Student.date_of_birth) }}</div>
                </div>
                <div style="margin-bottom: 10px">
                    {{ form_row(Student.study_groups) }}
                </div>
                <div style="margin-bottom: 50px">
                    {{ form_label(Student.imageFile) }}
                    {{ form_widget(Student.imageFile) }}
                    <div style="color: #ff0000">{{ form_errors(Student.imageFile) }}</div>
                </div>
            </div>

        {% endfor %}

        {{ form_end(form) }}

    <a class="students_back" href="{{ path('students') }}"><button type="submit" style="background-color: #e97d43; border-radius: 5px ;border: 0; width: 80px; height: 25px; color: #ffffff; margin-top: 10px">Back</button></a>

{% endblock %}

SAF/templates/views/index.html.twig
<!DOCTYPE html>
<head>
        <title>Student Administration Framework</title>
        <link rel="icon" type="image/png" href="{{ asset('images/saf_icon.png') }}" sizes="32x32"/>
        <link href="{{ asset('/css/style.css') }}" rel="stylesheet" type="text/css">
</head>

{% block body %}
        <div style="position: fixed; left: 50%; top: 50%; transform: translate(-50%, -50%)">
                <div><img src="{{ asset('images/saf_emblem.jpg') }}" alt="logo" class="logo">
                <h1>Student Administration Framework</h1>
                <a class="entry" href="{{ path('new_user') }}"><button type="submit" style="background-color: #34cbe0; color: #ffffff; border-color: #34cbe0; border-radius: 2px; margin-left: 50px ;width: 400px ;height: 50px">Entry for the website</button></a>
                <p style="text-align: center">Created by Boldizsár András</p>
        </div>
{% endblock %}

SAF/templates/views/new_sgroup.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Study Group{% endblock %}

{% block body %}

    <div style="position: fixed; left: 50%; top: 50%; transform: translate(-50%, -50%)">
        {{ form_start(form) }}

        <div style="margin-bottom: 10px">
            {{ form_row(form.group_name) }}
        </div>
        <div style="margin-bottom: 10px">
            {{ form_row(form.group_leader) }}
        </div>
        <div style="margin-bottom: 10px">
            {{ form_row(form.subject) }}
        </div>
        <div style="margin-bottom: 10px">
            {{ form_label(form.datetime_of_study_group) }}
            {{ form_widget(form.datetime_of_study_group) }}
            <div style="color: #ff0000">{{ form_errors(form.datetime_of_study_group) }}</div>
        </div>
        <div style="margin-bottom: 10px">
            {{ form_row(form.save) }}
        </div>

        {{ form_end(form) }}

    <a class="sgroups_back" href="{{ path('study_groups') }}"><button type="submit" style="background-color: #e97d43; border-radius: 5px ;border: 0; width: 80px; height: 25px; color: #ffffff">Back</button></a>
    </div>

{% endblock %}

SAF/templates/views/new_student.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Student{% endblock %}

{% block body %}

    <div style="position: fixed; left: 50%; top: 50%; transform: translate(-50%, -50%)">
        {{ form_start(form) }}

        <div style="margin-bottom: 10px">
            {{ form_row(form.name) }}
        </div>
        <div style="margin-bottom: 10px">
            {{ form_row(form.sex) }}
        </div>
        <div style="margin-bottom: 10px">
            {{ form_row(form.email_address) }}
        </div>
        <div style="margin-bottom: 10px">
            {{ form_row(form.place_of_birth) }}
        </div>
        <div style="margin-bottom: 10px">
            {{ form_label(form.date_of_birth) }}
            {{ form_widget(form.date_of_birth) }}
            <div style="color: #ff0000">{{ form_errors(form.date_of_birth) }}</div>
        </div>
        <div style="margin-bottom: 10px">
            {{ form_row(form.study_groups) }}
        </div>
        <div style="margin-bottom: 10px">
            {{ form_label(form.imageFile) }}
            {{ form_widget(form.imageFile) }}
            <div style="color: #ff0000">{{ form_errors(form.imageFile) }}</div>
        </div>
        <div style="margin-bottom: 10px">
            {{ form_row(form.save) }}
        </div>

        {{ form_end(form) }}

    <a class="students_back" href="{{ path('students') }}"><button type="submit" style="background-color: #e97d43; border-radius: 5px ;border: 0; width: 80px; height: 25px; color: #ffffff">Back</button></a>
    </div>

{% endblock %}

SAF/templates/views/new_user.html.twig
<title>New User</title>

<head>
    <link href="{{ asset('/css/style.css') }}" rel="stylesheet">
    <link rel="icon" type="image/png" href="{{ asset('images/saf_icon.png') }}" sizes="32x32"/>
</head>

{% block body %}
<div style="position: fixed; left: 50%; top: 50%; transform: translate(-50%, -50%)">
    {% if(users|length < 1) %}
    <div>
        <h1>Please first create an user for this website!</h1>
    </div>

    <div style="position: fixed; left: 50%; top: 50%; transform: translate(-50%, -50%)">
        {{ form_start(form) }}

        <div style="margin-bottom: 10px">
            {{ form_row(form.username) }}
        </div>
        <div style="margin-bottom: 10px">
            {{ form_row(form.email_address) }}
        </div>
        <div style="margin-bottom: 10px">
            {{ form_row(form.password) }}
        </div>
        <div style="margin-bottom: 10px">
            {{ form_row(form.imageFile) }}
        </div>
        <div style="margin-bottom: 10px">
            {{ form_row(form.save) }}
        </div>

        {{ form_end(form) }}
    </div>

    {% else %}
        <a href="{{ path('delete_all_users') }}"><p>You have already created an user, but if you want to change the user please use this link to delete that earlier user!</p></a>
        <a href="{{ path('students') }}"><button type="submit" style="background-color: #34cbe0; border-radius: 5px ;border: 0; width: 100px; height: 50px; color: #ffffff">Continue to the website</button></a>
    {% endif %}

    <a class="students_back" href="/"><button type="submit" style="background-color: #e97d43; border-radius: 5px ;border: 0; width: 80px; height: 25px; color: #ffffff">Back</button></a>
</div>
{% endblock %}

SAF/templates/views/students.html.twig
{% extends 'base.html.twig' %}

{% block title %}Student Administration Framework{% endblock %}

{% block body %}

    {% for message in app.flashes('result') %}
        <div class="flash">
            <p>{{ message }}</p>
        </div>
    {% endfor %}

    <div class="body-container">
        <a href="{{ path('students') }}">
            <div class="tab" style="background-color: #ffffff">
                <div class="tabp">
                    <p style="color: #36ccdd">STUDENTS</p>
                    <p style="color: #767779">{{ allStudents|length }} student registered</p>
                </div>
            </div>
        </a>


        <a href="{{ path('study_groups') }}">
            <div class="tab" style="margin: 5px; background-color: #f3f7fa">
                <div class="tabp">
                    <p style="color: #9ea8ae" >STUDY GROUPS</p>
                    <p style="color: #dadee1">{{ study_groups|length}} study groups with {{ student_in_groups}} students</p>
                </div>
            </div>
        </a>

        <table class="table">
            <tr class="firsttr">
                <td style="width: 25%">
                    <div class="show">
                        <p>SEARCH FOR NAME</p>
                        <form  id="search" method="POST" action="{{ path('studentsearch') }}">
                            <label for="inputname"></label><input type="search" name="nameSearch" id="inputname" class="searchname" placeholder="&#xf002">
                        </form>
                    </div>
                </td>
                <td style="width: 50%">
                    <i class="far fa-user"><b> {{ allStudents|length }} STUDENTS</b></i>
                    <button type="submit" class="editButton" form="deleteEditForm" name="editCheck" title="Edit" formaction="/students/edit-student"><i class="far fa-edit"></i></button>
                    <a class="newButton" href="{{ path('new_student') }}"><button type="submit" name="new" title="Create new student">New</button></a>
                </td>
                <td style="text-align: right; width: 25%">
                    {% if allStudents|length > 10 %}
                    {{ knp_pagination_render(students) }}
                    {% endif %}
                </td>
            </tr>
            <tr>
                <td>
                    <table style="margin-left: 40px">
                        <tr>
                            <td style="color: #a4acb0" colspan="2">FILTERS FOR STUDY GROUPS</td>
                        </tr>
                        <form id="filter" action="{{ path('group_filter') }}" method="POST">
                        {%  for study_group in study_groups %}
                        <tr>
                            <td style="width: 10%">
                                <label class="control control-checkbox">
                                <input type="checkbox" name="checkid[]" value="{{ study_group.id }}"  class="check"
                                        onchange="document.getElementById('filter').submit()">
                                    <div class="control_indicator"></div>
                                </label>
                                    </td>
                            <td>{{ study_group.groupname }}</td>
                        </tr>
                        {% endfor %}
                        </form>
                    </table>
                </td>
                <td colspan="3">

                        <form id="deleteEditForm" action="{{ path('delete_students') }}">
                    <table class="table" style="background-color: #ffffff; width: 97%; ">
                        <tr style="color: #a4acb0; border-bottom: 1px solid #f4f5f6">
                            <td>
                                <label class="control control-checkbox">
                                <input type="checkbox" value="select" name="checkAll" id="check" class="check" onclick="select_all()">
                                    <div class="control_indicator"></div>
                                </label>
                            </td>
                            <td style="width: 10%"></td>
                            <td style="width: 20%">NAME</td>
                            <td style="width: 10%">SEX</td>
                            <td style="width: 25%">PLACE AND DATE OF BIRTH</td>
                            <td style="text-align: right; width: 35%">GROUPS</td>
                        </tr>
                        {%  for student in students %}
                            <tr style="border-bottom: 1px solid #f4f5f6">
                                <td style="width: 10%">
                                    <label class="control control-checkbox">
                                        <input type="checkbox" name="id[]" value="{{ student.id }}" class="check">
                                        <div class="control_indicator"></div>
                                    </label>
                                </td>
                                <td>
                                    <img src="{{ asset('images/studentspics/' ~ student.studentImagefilename) }}" alt="photo" class="photo" width="59" height="59">
                                </td>
                                <td>{{ student.name }}</td>
                                <td>{{ student.sex }}</td>
                                <td>{{ student.placeofbirth }}, {{ student.dateofbirth|date("Y.m.d") }}</td>
                                <td style="text-align: right">
                                    {% for sgroup in student.studygroups|sort((a,b) => a.groupname <=> b.groupname) %}
                                        {% if loop.index == 1  and student.studygroups|length > 1 %}
                                            {{ sgroup.groupname }},
                                        {% elseif loop.index == 2 or student.studygroups|length == 1 %}
                                            {{ sgroup.groupname }}
                                        {% elseif loop.index == 3 %}
                                            and <span style="color: #e97d43"> {{ student.studygroups|length -  loop.index + 1}} more</span>
                                        {% endif%}
                                    {% endfor %}
                                </td>
                        </tr>
                        {% endfor %}
                    </table>
                    <button type="submit" class="deleteAll" name="deleteAllChecks">Delete</button>
                    </form>
                </td>
            </tr>
        </table>

    </div>
{% endblock %}

SAF/templates/views/study_groups.html.twig
{% extends 'base.html.twig' %}

{% block title %}Student Administration Framework{% endblock %}

{% block body %}

    {% for message in app.flashes('result') %}
        <div class="flash">
            <p>{{ message }}</p>
        </div>
    {% endfor %}

    <div class="body-container">
        <a href="{{ path('students') }}">
            <div class="tab" style="background-color: #f3f7fa">
                <div class="tabp">
                    <p style="color: #9ea8ae">STUDENTS</p>
                    <p style="color: #dadee1">{{ students|length }} student registered</p>
                </div>
            </div>
        </a>


        <a href="{{ path('study_groups') }}">
            <div class="tab" style="margin: 5px; background-color: #ffffff">
                <div class="tabp">
                    <p style="color: #36ccdd" >STUDY GROUPS</p>
                    <p style="color: #767779">{{ allStudy_groups|length }} study groups with {{ student_in_groups }} students</p>
                </div>
            </div>
        </a>

        <table class="table">
            <tr class="firsttr">
                <td style="width: 25%">
                    <div class="show">
                        <p>SEARCH FOR NAME</p>
                        <form method="POST" action="{{ path('groupsearch') }}">
                            <label for="inputname"></label><input type="search" style="width: 50%; height: 25px" name="nameSearch" id="inputname" class="searchname" placeholder="&#xf002">
                        </form>
                    </div>
                </td>
                <td style="width: 50%">
                    <i class="fas fa-users"><b> {{ allStudy_groups|length }} STUDY GROUPS</b></i>
                    <button type="submit"  class="editButton" form="deleteEditForm" name="editCheck" title="Edit" formaction="/study-groups/edit-studygroup"><i class="far fa-edit"></i></button>
                    <a class="newButton" href="{{ path('new_study_group') }}"><button type="submit" title="Create new study group">New</button></a>
                </td>
                <td style="text-align: right; width: 25%">
                    {% if allStudy_groups|length > 10 %}
                    {{ knp_pagination_render(study_groups) }}
                    {% endif %}
                </td>
            </tr>
            <tr>
                <td>
                    <table style="margin-left: 40px">
                        <tr>
                            <td style="color: #a4acb0" colspan="2">FILTERS FOR STUDENTS</td>
                        </tr>
                        <form id="filter" action="{{ path('student_filter') }}" method="POST">
                            {%  for student in students %}
                                <tr>
                                    <td style="width: 10%">
                                        <label class="control control-checkbox">
                                            <input type="checkbox" name="checkid[]" value={{ student.id }} class="checkFilter"
                                                                  onchange="document.getElementById('filter').submit()">
                                            <div class="control_indicator"></div>
                                        </label>
                                    </td>
                                    <td>{{ student.name }}</td>
                                </tr>
                            {% endfor %}
                        </form>
                    </table>
                </td>
                <td colspan="3">

                    <form id="deleteEditForm" action="{{ path('delete_study_groups') }}">

                    <table class="table" style="background-color: #ffffff; width: 97%">
                        <tr style="color: #a4acb0; border-bottom: 1px solid #f4f5f6">
                            <td style="width: 10%">
                                <label class="control control-checkbox">
                                    <input type="checkbox" value="select" name="checkAll" id="check" class="checkAll" onclick="select_all()">
                                    <div class="control_indicator"></div>
                                </label>
                            </td>
                            <td style="width: 15%">GROUP NAME</td>
                            <td style="width: 15%">GROUP LEADER</td>
                            <td style="width: 10%">SUBJECT</td>
                            <td style="width: 20%">DATE AND TIME</td>
                            <td style="text-align: right; width: 29%">ENROLLED STUDENTS</td>
                        </tr>
                        {%  for study_group in study_groups %}
                        <tr style="border-bottom: 1px solid #f4f5f6">
                            <td style="width: 10%">
                                <label class="control control-checkbox">
                                    <input type="checkbox" name="id[]" value="{{ study_group.id }}" class="check">
                                    <div class="control_indicator"></div>
                                </label>
                            </td>
                            <td>{{ study_group.groupname }}</td>
                            <td>{{ study_group.groupleader }}</td>
                            <td>{{ study_group.subject }}</td>
                            <td>{{ study_group.datetimeofstudygroup|date("Y.m.d H:i") }}</td>
                            <td style="text-align: right">
                                {% for student in study_group.enrolledstudents|sort((a,b) => a.name <=> b.name) %}
                                    {% if loop.index == 1 and study_group.enrolledstudents|length > 1 %}
                                        {{ student.name }},
                                    {% elseif loop.index == 2  or study_group.enrolledstudents|length == 1 %}
                                        {{ student.name }}
                                    {% elseif loop.index == 3 %}
                                        and <span style="color: #e97d43"> {{ study_group.enrolledstudents|length -  loop.index + 1}} more</span>
                                    {% endif%}
                                {% endfor %}
                            </td>
                        </tr>
                        {% endfor %}
                    </table>
                        <button type="submit" class="deleteAll" id="deleteAllChecks">Delete</button>
                    </form>
                </td>
            </tr>
        </table>

    </div>
{% endblock %}

SAF/templates/views/user_settings.html.twig
{% extends 'base.html.twig' %}

{% block title %}User Settings{% endblock %}

{% block body %}

    <div style="position: fixed; left: 50%; top: 50%; transform: translate(-50%, -50%)">
        {{ form_start(form) }}

        <div style="margin-bottom: 10px">
            {{ form_row(form.username) }}
        </div>
        <div style="margin-bottom: 10px">
            {{ form_row(form.email_address) }}
        </div>
        <div style="margin-bottom: 10px">
            {{ form_row(form.password) }}
        </div>
        <div style="margin-bottom: 10px">
            {{ form_label(form.imageFile) }}
            {{ form_widget(form.imageFile) }}
            {{ form_errors(form.imageFile) }}
        </div>
        <div style="margin-bottom: 10px">
            {{ form_row(form.save) }}
        </div>

        {{ form_end(form) }}

    <a class="students_back" href="{{ path('students') }}"><button type="submit" style="background-color: #e97d43; border-radius: 5px ;border: 0; width: 80px; height: 25px; color: #ffffff">Back</button></a>
    </div>

{% endblock %}